@startuml composite

class Client

interface Component {
  + operation()
}

class Leaf {
  + operation()
}

class Composite {
  + operation()
  + add(Component component)
}

Client --> Component

Leaf ..|> Component
Composite ..|> Component
Composite o--> Component

@enduml