@startuml factory-method

class Developer {
  + createWebsite(string name)
}

interface WebsiteFactory {
  - Dictionary<string name, Type type> types
  + createWebsite(string name)
}

class Website

class ReactWebsite
class VueWebsite

Developer --> WebsiteFactory
WebsiteFactory --> Website

ReactWebsite ..|> Website
VueWebsite ..|> Website

@enduml